# Generated by Django 2.1.1 on 2018-09-30 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLMapper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('long_url', models.URLField(db_index=True, max_length=500, unique=True)),
                ('short_url', models.URLField(db_index=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='urldetails',
            name='url_mapping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.URLMapper'),
        ),
    ]
